# Generated by Django 6.0.2 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leopardsighting',
            name='location_name',
            field=models.CharField(default='Unknown location', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leopardsighting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='leopardsighting',
            index=models.Index(fields=['latitude'], name='sightings_l_latitud_71f8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='leopardsighting',
            index=models.Index(fields=['longitude'], name='sightings_l_longitu_56b8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='leopardsighting',
            index=models.Index(fields=['created_at'], name='sightings_l_created_6ef917_idx'),
        ),
    ]
