# Generated by Django 6.0.2 on 2026-03-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_leopardsighting_location_name_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leopardsighting',
            new_name='sightings_l_latitud_6a05ed_idx',
            old_name='sightings_l_latitud_71f8ec_idx',
        ),
        migrations.RenameIndex(
            model_name='leopardsighting',
            new_name='sightings_l_longitu_60a01d_idx',
            old_name='sightings_l_longitu_56b8cd_idx',
        ),
        migrations.RenameIndex(
            model_name='leopardsighting',
            new_name='sightings_l_created_c800b2_idx',
            old_name='sightings_l_created_6ef917_idx',
        ),
    ]
