# Generated by Django 6.0.2 on 2026-07-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_device_token_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leopardsighting',
            name='status',
        ),
    ]
