# Generated by Django 6.0.2 on 2026-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_departments_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sighting_radius_km',
            field=models.FloatField(default=5),
        ),
    ]
